### ISSUE TITLE
Add examples of using ansi-terminal

### ISSUE THREAD

**Issue by MaxGabriel** [MaxGabriel/Haskell-Documentation#17]
> I'm not very familiar with Haskell terminal libraries. Maybe people use something else?

ansi-terminal has a high number of downloads (1105 in the past month). It doesn't look too complicated, but it requires combining some pieces together it seems like. I'd like it to be immediately obvious how to do basic things, like print colored text. Potentially you can come up with other common tasks terminal programs do to add as examples?

http://hackage.haskell.org/package/ansi-terminal-0.6.2.2/docs/System-Console-ANSI.html

**Comment by MaxGabriel** [comment]
Alex is working on this

**Comment by chexxor** [comment]
I slightly improved the hackage page's docs with https://github.com/feuerbach/ansi-terminal/pull/9. Still plenty of room for improvement, though!

**Comment by MaxGabriel** [comment]
Nice work
